api_login_check:
    path: /login

user.me:
  path: /me
  methods: GET
  controller: App\Controller\User\MeController

guest:
  resource: routes/guest.yaml
  prefix: '/guest'
  trailing_slash_on_root: false

challenge:
  resource: routes/challenge.yaml
  prefix: '/challenge'
  trailing_slash_on_root: false

activity:
  resource: routes/activity.yaml
  prefix: '/activity'
  trailing_slash_on_root: false

enum:
  resource: routes/enum.yaml
  prefix: '/enum'
  trailing_slash_on_root: false